"""editing table

Revision ID: 9e4ddab5b7ba
Revises: b734f59ad3c3
Create Date: 2020-03-18 11:55:45.482123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e4ddab5b7ba'
down_revision = 'b734f59ad3c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.VARCHAR(length=250), nullable=True))
    # ### end Alembic commands ###
